#language: ruby
sudo: false
#rvm:
#  - 2.3.0
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
    - env: EMACS_VERSION=24.5
cache:
  - bundler
  - directories:
      - "$HOME/emacs"
env:
  global:
    - secure: "OuV0dOHf1MIZelQuV8Z1jH6Zm6HnS1J9cpVpF85T7/NNCEjgHWDfMcU4wYmFoJM+qzc/L2vqZRnyB1Ak/9DHB4L8MGCB8BllTN4nxOGhhg1rbbv9jIO0JhLzKeJzFiNxrw0uLAgQUx2p/HNc/SID3SNMoQxi/rOX22eiaMfGWxTVQDh2EFyv9Krk7N+QpXO/q2QYuF9cXUYOyVeqluqEFby97urt1FsJOvRdCsLmmGWlKRDka8yX2+ZmyNYslN/SGUS90EKYGmwk9iiSWN6lTq1zEKkO3gJMEXlpgmG229jYvYdodE7zu14CBGKKp17zQFIanDdr+wIzTV4LQnxROAjORbvgt5r6meVcJafMMWVbhJ5U/YLxYqKZhRNsetL5AVc4rGuVMVwujZ4YSekJsMaeOlDyGBlyadkdDbogFSUvHK7E05GgeXSFR6hGE1KWqISNGSS3TJtlGo56H5n9Kyh7qXEszofaiigx6X8E5FjzUCQGlDDMFGdgfMDw2UPXj/Ngwyhw/IhFEy/A77DvylBABwGTz4w8bndqNhb6rVOu5Kc0tcEYxcbP1579HFXNQAtVbe0uuyvP59dNSuOLgcwcx6X6X5fWRRVkm04cgOSeRRnzlPHu5r/Um0D41NSDTDm7bfmyd87hWM1YYwnRFH/Xw5ytOE5NlqZ+z4w9ukI="
  matrix:
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.1-rc2
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - mkdir bin/
  - wget -P bin/screenfetch https://raw.githubusercontent.com/KittyKatt/screenFetch/master/screenfetch-dev
  - chmod +x bin/screenfetch
  - git clone https://github.com/saitoha/seq2gif.git
  - cd seq2gif && ./configure --prefix=$TRAVIS_BUILD_DIR && make && make install && cd ..

addons:
  apt:
    packages:
      - ttyrec
after_success:
  - .travis/push.sh
script:
  - stty rows 24
  - stty columns 80
  - echo -e "lines\ncols"|tput -S
  - stty size
  - if [[ -n $EMACS_VERSION ]]; then make -f emacs-travis.mk install_emacs; fi
#  - "./run-ci.sh minimal.el"
  - "./run-ci.sh vanilla.el"
#  - "./run-ci.sh themes.el"

