#language: ruby
sudo: false
#rvm:
#  - 2.3.0
matrix:
  fast_finish: true
  allow_failures:
    - env: EMACS_VERSION=snapshot
    - env: EMACS_VERSION=24.5
cache:
  - bundler
  - directories:
      - "$HOME/emacs"
env:
  global:

    - secure: "KgPtSX78ALwjc75J2CyR+hi/GMgcivXHU4xRsw2jfGTlNblp6IJF7uB5iHxx5mTEZe2nAjNoJooTWdKr0NOhnsLYwV+FJcpRsn/BY3qVgKjPC0LDObl0kNq74HwsxMvQbyiJdRuGB+rYP2ZeWLp03R5AorsbUy2mNXX7xEomnLhbBkwDankO/hgyDfkM0gahejk4oap0lYqEn3xbGgHdbg0cte3uXQflZdpU+dFaIZAJc6abSUq2M1IDFqfdgSfpoYPe9/x4hQlu4/dzQN0ZGsJ/hyx8h1+J4CX1VQMIXAVhn7rmWNCwGxREvI99WP1jB2omr+AcErRG89j4d/j2uqtQrMe4wTAa8PDArbkaEez1hfxaU/x3DCLTst+9iL1C6OCphRb8BpOSVajaJ8vpiVOVMJfubSzUkQLT9PlV29EaLzWFrRsQ+JVRH0Fv2a7QuX4os4JUL35HaMbF814+8dv68nnsWWxDuVzD/zdqbTgM1BI4fXB8QHXjK5ORgDiCuUnuLsXvGnXlzCRoLx9IeAYqXNkrKbtuFMOwedoi7edb/IU3GQM7k+gU6Mmn3BZXMuHLcYhhCkImWMG05mgnIaAtp8oVVdvperhf6ZlR3jkHScNyCgT5MIykBugeJD+xaunge+B+w058Ku+qO58vnNAm4108a7O1o6iLjVNIlr8="
  matrix:
    - EMACS_VERSION=24.5
    - EMACS_VERSION=25.1-rc2
    - EMACS_VERSION=25.1
    - EMACS_VERSION=25.2
    - EMACS_VERSION=snapshot
before_install:
  - export PATH="$HOME/bin:$PATH"
  - mkdir bin/
  - wget -P bin/screenfetch https://raw.githubusercontent.com/KittyKatt/screenFetch/master/screenfetch-dev
  - chmod +x bin/screenfetch
  - git clone https://github.com/saitoha/seq2gif.git
  - cd seq2gif && ./configure --prefix=$TRAVIS_BUILD_DIR && make && make install && cd ..

addons:
  apt:
    packages:
      - ttyrec
after_success:
  - .travis/push.sh
script:
  - stty rows 24
  - stty columns 80
  - echo -e "lines\ncols"|tput -S
  - stty size
  - if [[ -n $EMACS_VERSION ]]; then make -f emacs-travis.mk install_emacs; fi
#  - "./run-ci.sh minimal.el"
  - "./run-ci.sh vanilla.el"
#  - "./run-ci.sh themes.el"

